$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = '6.06 custompins'
  app.frameworks += %w(CoreLocation MapKit)
end
