$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = '6.08addresslonglat'
  app.frameworks += %w(CoreLocation MapKit)
end
