$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = '9.05 audiooversounds'
  app.frameworks += %w(AVFoundation)
end
