# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = '03_accessing_calendar_content'
  app.frameworks += %w(EventKit EventKitUI)
end
